// CV data (/curriculo). Kept apart from content.ts so the home page bundle
// doesn't carry it; Tavo reads it on the server too.

// Dados completos e precisos extraídos do Lattes e LinkedIn
export const cvData = {
  profile: {
    name: "Gustavo Simas da Silva",
    titles: "Doutorando e Mestre em Engenharia e Gestão do Conhecimento (UFSC) · Engenheiro Eletrônico (UFSC)",
    role: "Analista Técnico II - Inteligência Artificial no Sebrae/SC · Pesquisador Bolsista CAPES (LaMiD/UFSC) · Escritor e Produtor Fonográfico",
    location: "Florianópolis, Santa Catarina, Brasil",
    email: "contato@gustavosimas.com",
    lattesUrl: "http://lattes.cnpq.br/3423329196677574",
    lattesId: "3423329196677574",
    orcidUrl: "https://orcid.org/0000-0003-3485-7910",
    orcidId: "0000-0003-3485-7910",
    linkedinUrl: "https://www.linkedin.com/in/simasgs",
    spotifyUrl: "https://open.spotify.com/artist/6WjZVnEMXM9OzuqDhdrvUz",
    githubUrl: "https://github.com/GSimas",
    bio: "Energizar o saber, reduzir o desconhecimento e potencializar a inovação transformadora. Atua ao entender a complexidade gerenciando caos e ordem por meio de Engenharia, Gestão e Mídias do Conhecimento, Inovação, Tecnologia e Arte. Atualmente é Analista de IA no Sebrae/SC, pesquisador bolsista CAPES de doutorado no Laboratório de Mídias (LAMID/PPGEGC/UFSC), escritor e produtor fonográfico.",
  },
  experience: [
    {
      period: "06/2026 — Presente",
      role: "Analista Técnico II — Inteligência Artificial",
      company: "Sebrae Santa Catarina",
      location: "Florianópolis, SC",
      bullets: [
        "Estruturação e operação da governança do Escritório de IA do Sebrae/SC.",
        "Monitoramento, análise e validação da execução de projetos corporativos de IA nas áreas técnicas e meio, assegurando conformidade metodológica e qualidade.",
        "Apoio a áreas na elaboração de planos de projetos de IA, matrizes de risco, cronogramas, indicadores e resultados esperados.",
        "Acompanhamento de projetos estratégicos de IA de origem nacional alinhados ao Sebrae Nacional.",
        "Condução de avaliações técnicas e de conformidade de casos de uso de IA; desenho e padronização do ciclo de vida de soluções (do piloto à produção).",
        "Implantação e manutenção de métricas e monitoramento de desempenho de IA (MLOps/LLMOps em nível de gestão) e orquestração de capacitações para adoção institucional.",
      ],
    },
    {
      period: "03/2025 — Presente",
      role: "Pesquisador Bolsista de Doutorado (CAPES)",
      company: "Universidade Federal de Santa Catarina (UFSC)",
      location: "Florianópolis, SC",
      bullets: [
        "Bolsista pesquisador CAPES no Laboratório de Mídias (LAMID) do Programa de Pós-Graduação em Engenharia, Gestão e Mídia do Conhecimento (PPGEGC/UFSC).",
        "Pesquisa avançada em ecologia do conhecimento, ciência de redes, cientometria, inteligência artificial e governança tecnológica.",
        "Investigação de aspectos sociotécnicos do conhecimento em rede (estruturação e impacto de tecnologias como IA em contextos organizacionais e acadêmicos).",
      ],
    },
    {
      period: "03/2025 — Presente",
      role: "Revisor Científico (Reviewer)",
      company: "Science Publishing Group",
      location: "Internacional",
      bullets: [
        "Avaliação crítica por pares (peer review) de artigos científicos de ponta nas áreas de tecnologia, inteligência artificial e gestão do conhecimento.",
      ],
    },
    {
      period: "01/2024 — 06/2026",
      role: "Consultor em Inovação, Dados e Governança",
      company: "Consultoria Autônoma / Negócios",
      location: "Florianópolis, SC",
      bullets: [
        "Consultoria em inovação, dados, inteligência artificial, gestão do conhecimento e governança tecnológica.",
        "Aplicação de metodologias para diagnóstico e planejamento organizacional, monitoramento de indicadores e gestão da mudança.",
      ],
    },
    {
      period: "08/2023 — 04/2026",
      role: "Analista de Inovação Sênior",
      company: "Impact Hub Brasil",
      location: "Florianópolis, SC",
      bullets: [
        "Pesquisa, Desenvolvimento e Inovação (P&D&I) para impacto socioambiental positivo.",
        "Desenvolvimento e implementação de metodologias para Ecossistemas Locais de Inovação e Impacto (coautor da Metodologia ALI Ecossistemas).",
        "Inteligência de negócios, pesquisas de tendências e tecnologias emergentes.",
        "Avaliação e monitoramento de impacto socioambiental com visão sistêmica e relatórios executivos.",
        "Gestão e engenharia do conhecimento para capturar, compartilhar e disseminar práticas organizacionais.",
      ],
    },
    {
      period: "12/2021 — 08/2023",
      role: "Analista de Dados",
      company: "Impact Hub Brasil",
      location: "Florianópolis, SC",
      bullets: [
        "Análise de dados na área de ecossistemas de inovação e impacto socioambiental.",
        "Estruturação de pipelines analíticos, inteligência de negócios, governança da informação organizacional e cultura de aprendizagem.",
      ],
    },
    {
      period: "04/2020 — 01/2024",
      role: "Cofundador, Produtor Fonográfico e Engenheiro de Áudio",
      company: "VI Mídia Produtora (Visão Inclusiva)",
      location: "Florianópolis, SC",
      bullets: [
        "Cofundador e produtor fonográfico de conteúdos acessíveis para educação e entretenimento.",
        "Produção de audiolivros, audiodescrição para público print disabled e síntese vocal com recursos de IA.",
        "Engenharia de áudio, design de som e processamento digital de sinais de voz.",
        "Titular de marca registrada de serviço homologada no INPI.",
      ],
    },
    {
      period: "04/2020 — 01/2021",
      role: "Editor e Revisor Literário",
      company: "Editora Noveland",
      location: "Florianópolis, SC",
      bullets: [
        "Revisão textual e literária, avaliação e parecer de originais, coordenação editorial e gestão de marca.",
      ],
    },
    {
      period: "07/2018 — 02/2020",
      role: "Bolsista de Iniciação Científica (P&D Robótica)",
      company: "Laboratório de Robótica Aplicada (LAR/UFSC)",
      location: "Florianópolis, SC",
      bullets: [
        "P&D de Sistema Robotizado de Inspeção para Linhas de Distribuição de Energia Elétrica (convênio Celesc / Departamento de Engenharia Mecânica).",
        "Revisão sistemática de literatura, modelagem CAD/Solidworks, patentes, artigos científicos e desenvolvimento de interfaces/aplicações web (front-end).",
      ],
    },
    {
      period: "01/2017 — 02/2018",
      role: "Estagiário de Engenharia",
      company: "CIASC — Centro de Informática e Automação de SC",
      location: "Florianópolis, SC",
      bullets: [
        "Desenvolvimento de sistema de monitoramento preditivo para Data Center.",
        "Sensoriamento e alerta de variáveis críticas (temperatura, umidade, inundação, incêndio) com Zabbix, Arduino e Fluidodinâmica Computacional (CFD).",
      ],
    },
    {
      period: "02/2015 — 07/2015",
      role: "Estagiário de Engenharia Clínica (GTMH)",
      company: "Instituto de Engenharia Biomédica (IEB-UFSC / Carmela Dutra)",
      location: "Florianópolis, SC",
      bullets: [
        "Gestão de Tecnologia de Equipamentos Médico-Hospitalares (GTMH), controle de qualidade, manutenção corretiva/preventiva e treinamento técnico.",
      ],
    },
  ],
  education: [
    {
      period: "01/2025 — 03/2029 (Em andamento)",
      degree: "Doutorado em Engenharia, Gestão e Mídia do Conhecimento",
      institution: "Universidade Federal de Santa Catarina (UFSC)",
      details:
        "Bolsista CAPES. Orientadora: Profa. Dra. Vânia Ribas Ulbricht. Foco em Ecologia do Conhecimento, Ciência de Redes, Cientometria, Inteligência Artificial e Governança Sociotécnica.",
    },
    {
      period: "01/2025 — 03/2026 (Em andamento)",
      degree: "MBA em Tecnologia para Negócios: AI, Data Science e Big Data",
      institution: "PUCRS — Pontifícia Universidade Católica do RS",
      details: "Especialização executiva (364 horas) em inteligência artificial aplicada a modelos de negócio, Big Data e tomada de decisão estratégica.",
    },
    {
      period: "02/2023 — 02/2025 (Concluído)",
      degree: "Mestrado em Engenharia e Gestão do Conhecimento",
      institution: "Universidade Federal de Santa Catarina (UFSC)",
      details:
        "Dissertação: 'ECO-CAOS: um metamodelo conceitual para ecossistemas de conhecimento e culturas de aprendizagem organizacional'. Bolsista CAPES. Orientadora: Dra. Vânia Ribas Ulbricht. Vencedor do Prêmio SBGC de Melhor Dissertação do Brasil.",
    },
    {
      period: "02/2016 — 12/2021 (Concluído)",
      degree: "Bacharelado em Engenharia Eletrônica",
      institution: "Universidade Federal de Santa Catarina (UFSC)",
      details:
        "TCC: 'Algoritmo Adaptativo para Redução de Ruído e Preservação de Pistas Acústicas Biauriculares para Aparelhos Auditivos'. Orientador: Prof. Dr. Márcio Holsbach Costa. Ênfase em Processamento Digital de Sinais e Áudio.",
    },
    {
      period: "2012 — 2016 (Concluído)",
      degree: "Curso Técnico em Eletrônica",
      institution: "Instituto Federal de Santa Catarina (IFSC)",
      details: "Formação técnica de nível médio integrada, com fundamentação em circuitos, instrumentação e sistemas embarcados.",
    },
  ],
  certifications: [
    { name: "Data Product Manager Nanodegree", issuer: "Udacity", year: "2021-2022", hours: "160h" },
    { name: "Deep Learning Specialization", issuer: "Coursera / deeplearning.ai", year: "2018", hours: "300h" },
    { name: "Python Programming", issuer: "Coursera", year: "2018", hours: "300h" },
    { name: "Introduction to Linear Models and Matrix Algebra", issuer: "edX / HarvardX", year: "2023" },
    { name: "Digital Marketing Channels: Planning", issuer: "Coursera", year: "2018", hours: "300h" },
    { name: "KM Brasil — Gestão do Conhecimento", issuer: "SBGC", year: "2023" },
  ],
  awards: [
    {
      year: "2025",
      title: "Prêmio SBGC — Melhor Dissertação de Mestrado",
      entity: "Sociedade Brasileira de Gestão do Conhecimento (SBGC)",
      description: "Reconhecimento nacional pela dissertação ECO-CAOS sobre ecossistemas de conhecimento e cultura de aprendizagem.",
    },
    {
      year: "2022",
      title: "Seleção na Série 'Histórias do Cotidiano'",
      entity: "Biblioteca Universitária (BU/UFSC)",
      description: "Trabalho literário selecionado para acervo e divulgação cultural institucional.",
    },
    {
      year: "2020",
      title: "Aprovado no Programa Centelha",
      entity: "FAPESC / MCTI / Finep",
      description: "Subvenção e fomento governamental à inovação tecnológica e empreendedorismo para a VI Mídia.",
    },
    {
      year: "2020",
      title: "Seleção no Concurso de Fotografia Documentária",
      entity: "Floripa Anônima",
      description: "Registro documental da paisagem urbana e memória social da Ilha de Santa Catarina.",
    },
    {
      year: "2016",
      title: "I Prêmio IFSC de Literatura — Seleção Fotográfica",
      entity: "Instituto Federal de Santa Catarina (IFSC)",
      description: "Premiação de ensaio visual e fotográfico autoral.",
    },
    {
      year: "2015",
      title: "Premiado no Concurso Literário Fragmentos do Medo",
      entity: "Três Macacos Premiações",
      description: "Publicação em antologia de microcontos de circulação nacional.",
    },
    {
      year: "2014",
      title: "Premiado no I Concurso de Contos do IFSC",
      entity: "Instituto Federal de Santa Catarina (IFSC)",
      description: "Primeiro lugar e menção honrosa na categoria prosa de ficção.",
    },
    {
      year: "2015 — 2018",
      title: "Inspiration Award & Rookie All-Star Award",
      entity: "FIRST Robotics Competition (Equipe FRC 5800 Magic Island Robotics)",
      description: "Prêmios de liderança, comunicação e impacto comunitário em engenharia robótica.",
    },
    {
      year: "2009, 2010, 2011",
      title: "Três Menções Honrosas consecutivas",
      entity: "Olimpíada Brasileira de Matemática das Escolas Públicas (OBMEP)",
      description: "Destaque acadêmico em raciocínio lógico e resolução de problemas matemáticos.",
    },
  ],
  allPublications: [
    {
      type: "Livro",
      year: "2025",
      citation: "SIMAS DA SILVA, Gustavo. E o que eu faço com isso?. 1. ed. São Paulo: Labrador, 2025. 112p.",
      link: "https://www.instagram.com/tudoemsimas/",
    },
    {
      type: "Livro",
      year: "2025",
      citation: "SIMAS DA SILVA, Gustavo. Tecnogonia: criando tecnologias que nos criam. 1. ed. Belo Horizonte: Caravana Grupo Editorial, 2025.",
      link: "https://caravanagrupoeditorial.com/livros/tecnogonia-criando-tecnologias-que-nos-criam/?v=2d3615d82bb9",
    },
    {
      type: "Livro",
      year: "2021",
      citation: "ZIMMERMANN, D.; SILVA, Gustavo Simas da (Orgs.). Antologia Pandemias. 1. ed. Florianópolis: Noveland, 2021. v. 1. 310p.",
    },
    {
      type: "Artigo Periódico",
      year: "2026",
      citation: "SILVA, Gustavo Simas da; ULBRICHT, V. R. An ESG-AI Matrix for Innovation Ecosystems. Sustainable Business International Journal, v. 1, p. 1-30, 2026.",
      link: "https://periodicos.uff.br/sbijournal/article/view/63124",
    },
    {
      type: "Artigo Periódico",
      year: "2026",
      citation: "SILVA, Gustavo Simas da; ULBRICHT, Vania Ribas. Technonecromancy: Simulacra of Presence and the Politics of Death in the Age of Generative Artificial Intelligence. Trilogía Ciencia Tecnología Sociedad, v. 18, p. 1-23, 2026.",
      link: "https://revistas.itm.edu.co/index.php/trilogia/article/view/3194",
    },
    {
      type: "Artigo Periódico",
      year: "2026",
      citation: "DA SILVA, Gustavo Simas; ULBRICHT, Vânia Ribas. Promptography and the reconfiguration of human creative agency. Revista Brasileira de Estudos CTS, v. 1, p. 38-59, 2026.",
      link: "https://revistabrasileiradeestudoscts.emnuvens.com.br/cts/article/view/100",
    },
    {
      type: "Artigo Periódico",
      year: "2025",
      citation: "AGUIAR, M.; SIMAS DA SILVA, Gustavo. Trajetórias de mulheres negras no ensino superior: barreiras, conquistas e caminhos para avanço. Aracê - Direitos Humanos em Revista, v. 7, p. 35563-35591, 2025.",
      link: "https://arace.emnuvens.com.br/arace/article/view/1012",
    },
    {
      type: "Artigo Periódico",
      year: "2025",
      citation: "SIMAS DA SILVA, Gustavo; LIMA, L. S.; ULBRICHT, V. R. Festival de aprendizagem como mobilizador do ecossistema de conhecimento organizacional. Caderno Pedagógico, v. 22, p. 1, 2025.",
      link: "https://ojs.studiespublicacoes.com.br/ojs/index.php/cadped/article/view/12975",
    },
    {
      type: "Artigo Periódico",
      year: "2025",
      citation: "DA SILVA, Gustavo Simas. Esperança e Psicopolítica em Superman (2025): Uma análise à luz das categorias de Byung-Chul Han. Lumen et Virtus, v. 16, p. 9548-9574, 2025.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Artigo Periódico",
      year: "2025",
      citation: "SILVA, Gustavo Simas da. Entre a dor pessoal e o sofrimento estrutural: uma crítica decolonial a Sociedade Paliativa de Byung-Chul Han. Lumen et Virtus, v. 16, p. 7889, 2025.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Artigo Periódico",
      year: "2025",
      citation: "SILVA, Gustavo Simas da; ULBRICHT, Vânia Ribas. Cidades inteligentes e sustentáveis? Uma análise comparativa dos índices CSC e IDSC em Florianópolis. Revista Políticas Públicas & Cidades, v. 14, p. e2686, 2025.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Artigo Periódico",
      year: "2025",
      citation: "SIMAS DA SILVA, Gustavo; RIBAS ULBRICHT, VÂNIA. A quantitative analysis of geographic, gender, and age distribution of Nobel Prize Laureates (1901-2025). International Journal of Knowledge Engineering and Management, v. 14, p. 1-17, 2025.",
      link: "https://ijkem.emnuvens.com.br/ijkem/article/view/287",
    },
    {
      type: "Artigo Periódico",
      year: "2025",
      citation: "DA SILVA, Gustavo Simas; ULBRICHT, Vânia Ribas. Padrões de Sustentabilidade: Uma análise de conceitos formais dos Objetivos de Desenvolvimento Sustentável nos estados brasileiros. Revista de Geopolítica, v. 16, p. e1096, 2025.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Artigo Periódico",
      year: "2025",
      citation: "SILVA, Gustavo Simas da. Narrativização como arquitetura temporal da memória. Revista Letras (Curitiba), v. 111, p. 1-50, 2025.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Artigo Periódico",
      year: "2023",
      citation: "DA SILVA, Gustavo Simas; LIMA, L. S.; FERRAZ, M. Z. Ecossistema de Conhecimento Organizacional: a visão sistêmica da interação entre Gestão do Conhecimento e Cultura de Aprendizagem. Inteligência Empresarial e Economia dos Intangíveis, v. 47, p. 1, 2023.",
      link: "https://repositorio.ufsc.br/handle/123456789/264422",
    },
    {
      type: "Capítulo",
      year: "2025",
      citation: "SILVA, Gustavo Simas da; ROSA, D. C.; FRANCO, L. H. R.; RAMOS, F. M.; ULBRICHT, V. R. Tecnologias para ouvir e comunicar: acesso, cultura e direitos de surdos e deficientes auditivos. In: Engenharia, Gestão e Inovação - Vol. 21. Poisson, 2025, p. 148-168.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Capítulo",
      year: "2025",
      citation: "RAMOS, F. M.; SILVA, Gustavo Simas da; FRANCO, J. A. S.; FRANCO, L. H. R.; SILVA, M. D.; ULBRICHT, V. R. Envelhecimento e inclusão: a importância da libras na comunicação com idosos surdos. In: Ciências Humanas e Sociais - Vol. 8. Poisson, 2025, p. 125-135.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Capítulo",
      year: "2024",
      citation: "SIMAS DA SILVA, Gustavo; ULBRICHT, V. R.; VANZIN, T. Cidades Criativas UNESCO no Brasil e Economia Criativa em Ecossistemas Locais de Inovação: uma análise de indicadores. In: Ebook VIA TCDS 2. Florianópolis: Via Estação Conhecimento, 2024, v. 2, p. 15-40.",
      link: "https://via.ufsc.br/wp-content/uploads/ebook-VIA-TCDS-2-1.pdf",
    },
    {
      type: "Capítulo",
      year: "2024",
      citation: "SILVA, Gustavo Simas da; ULBRICHT, Vânia Ribas; VANZIN, Tarcísio. Gestão em Ecossistemas de Inovação: Modelo de banco de dados para governança ecossistêmica. In: Perspectivas em Engenharia, Mídias e Gestão do Conhecimento - Vol. 5. Arquétipos, 2024, p. 115-134.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Capítulo",
      year: "2024",
      citation: "DA SILVA, Gustavo Simas; ULBRICHT, Vânia Ribas. Learning with Conversational AI: ChatGPT and Bard/Gemini in Education. Cognition and Exploratory Learning in the Digital Age. Cham: Springer Nature Switzerland, 2024, p. 101-117.",
      link: "https://link.springer.com/chapter/10.1007/978-3-031-65881-5_7",
    },
    {
      type: "Congresso",
      year: "2024",
      citation: "SIMAS, Gustavo; RIBAS ULBRICHT, VÂNIA. Human-AI Interaction: An Analysis of Anthropomorphization and User Engagement in Conversational Agents with a Focus on ChatGPT. In: IHSI 2024 (Intelligent Human Systems Integration), Palermo, Itália, 2024.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Congresso",
      year: "2024",
      citation: "SIMAS DA SILVA, Gustavo; RIBAS ULBRICHT, VÂNIA. Design Feeling: a symmathetic approach for design processes. In: 15th International Conference on Applied Human Factors and Ergonomics (AHFE 2024), Nice, França, 2024.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Congresso",
      year: "2023",
      citation: "SIMAS DA SILVA, Gustavo. Towards Effective Ecosystems: A Framework for Mapping Knowledge Governance and Management Activities. In: 15th KMIS (Knowledge Management and Information Systems), Roma, Itália, 2023.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Congresso",
      year: "2023",
      citation: "SIMAS DA SILVA, Gustavo; VANZIN, T.; ULBRICHT, V. R. Entropy in Innovation and Creativity Measurement: An Integrative Review. In: XIII Congresso Internacional de Conhecimento e Inovação (ciKi), Florianópolis, 2023.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Congresso",
      year: "2023",
      citation: "SIMAS DA SILVA, Gustavo. Second Brain, GTD and Seek/Sense/Share: An Integration of Personal Knowledge Management Workflows. In: XIII Congresso Internacional de Conhecimento e Inovação (ciKi), Florianópolis, 2023.",
      link: "https://ciki.emnuvens.com.br/ciki/article/view/284",
    },
    {
      type: "Congresso",
      year: "2023",
      citation: "SIMAS DA SILVA, Gustavo; ULBRICHT, V. R. ChatGPT and Bard in Education: A Comparative Review. In: CELDA 2023, Funchal, Portugal, 2023.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
    {
      type: "Congresso",
      year: "2023",
      citation: "SIMAS DA SILVA, Gustavo; ULBRICHT, V. R.; FERRAZ, M. Z.; LIMA, L. S. Ecossistema de Conhecimento Organizacional: visão sistêmica entre Gestão do Conhecimento e Cultura de Aprendizagem. In: 18º KM Brasil, 2023.",
      link: "https://orcid.org/0000-0003-3485-7910",
    },
  ],
  artisticProduction: [
    {
      category: "Música & Fonografia",
      items: [
        "Rancho de Amor à Ilha (2026) — Releitura instrumental lofi do hino oficial de Florianópolis (composição original de Zininho), celebrando os 100 anos da Ponte Hercílio Luz.",
        "Berimbrasil (@brasil.wav) — Projeto de curadoria, valorização e difusão da música brasileira na cultura digital.",
        "Álbuns e Registros Fonográficos (2020-2024): ColoRio, CacofonIA, CacofonIA 2, Days, Slop, SinfonIA, Data! Data! Data!, Violando, Ruído, Marginal, Centauro, Radiola, Espectros, BON VIVANT, Frutaria, Rizomas, Ludic Dreams, Themes Songbook, Músicas Beta, Músicas Alfa, Quartos.",
        "Trilhas Sonoras Originais (2021): Heart of Darkness, 1984, O Marinheiro, Boats Against the Current, Triste Fim de Policarpo Quaresma, Hágil (com Gilberto Gil).",
      ],
    },
    {
      category: "Audiolivros & Inclusão",
      items: [
        "A Mecânica das Palavras (2022) — Audiolivro acessível.",
        "Retrato do Artista Quando Coisa (Manoel de Barros, 2021) — Adaptação fonográfica acessível.",
        "O Guardador de Rebanhos & O Marinheiro & Mensagem (Fernando Pessoa, 2020-2021) — Produção de audiolivro e audiodescrição.",
        "O Grande Gatsby (F. Scott Fitzgerald, 2021) — Audiolivro em áudio imersivo.",
      ],
    },
    {
      category: "Artes Visuais & Fotografia",
      items: [
        "Nemotom (2021) — Obra audiovisual e vídeo experimental.",
        "Floripa Anônima (2020) — Ensaio fotográfico documental.",
        "I Prêmio IFSC de Literatura (2017) — Série fotográfica premiada.",
      ],
    },
  ],
  projectsAndMethods: [
    {
      title: "Laboratório de Mídia e Inclusão Digital (LaMiD / UFSC)",
      period: "2023 — Atual",
      role: "Pesquisador / Integrante",
      description:
        "Levantamento, análise e sistematização das produções em acessibilidade digital e mídias do conhecimento como mediadores de inclusão sociotécnica para pessoas com deficiência.",
    },
    {
      title: "Metodologia ALI Ecossistemas",
      period: "2022",
      role: "Coautor / Desenvolvedor",
      description:
        "Metodologia técnica para diagnóstico, governança e ativação de Ecossistemas Locais de Inovação no Brasil, adotada pelo Sebrae e rede Impact Hub.",
    },
    {
      title: "Sistema Robotizado para Inspeção de Redes Elétricas (Celesc / LAR-UFSC)",
      period: "2018 — 2020",
      role: "Pesquisador bolsista de Iniciação Científica",
      description:
        "Projeto conceitual, prototipagem, patentes e interface web de robô para inspeção de linhas de distribuição de energia elétrica.",
    },
    {
      title: "Gestão de Tecnologia Médico-Hospitalar (CELEC / IEB-UFSC)",
      period: "2015",
      role: "Estagiário de Engenharia",
      description:
        "Estudo comparativo e gestão de detectores de batimento cardíaco fetal na Maternidade Carmela Dutra.",
    },
  ],
  skills: {
    governanceAndKnowledge: [
      "Governança de Inteligência Artificial",
      "Engenharia do Conhecimento",
      "Ecologia do Conhecimento",
      "Modelagem Conceitual de Sistemas",
      "Cultura de Aprendizagem Organizacional",
      "Ecossistemas Locais de Inovação (ELI)",
      "Gestão de Impacto Socioambiental",
    ],
    technical: [
      "MLOps e LLMOps (nível de gestão e ciclo de vida)",
      "Python (Pandas, NumPy, Scikit-Learn, PyTorch)",
      "TypeScript, React, Vite, Node.js",
      "Processamento Digital de Sinais (DSP de áudio/voz)",
      "Modelagem de Dados e Business Intelligence (BI)",
      "Tecnologia Assistiva e Acessibilidade Digital",
      "Engenharia de Prompt (Promptography)",
    ],
    languages: [
      { language: "Português", level: "Nativo" },
      { language: "Inglês", level: "Avançado / Fluente" },
      { language: "Espanhol", level: "Profissional" },
      { language: "Italiano", level: "Intermediário" },
      { language: "Francês", level: "Básico / Leitura" },
    ],
  },
};

export const cvDataEn = {
  ...cvData,
  profile: {
    ...cvData.profile,
    titles: "PhD Candidate and Master in Knowledge Engineering and Management (UFSC) · Electronics Engineer (UFSC)",
    role: "Technical Analyst II — Artificial Intelligence at Sebrae/SC · CAPES Doctoral Research Fellow (LaMiD/UFSC) · Writer and Record Producer",
    location: "Florianópolis, Santa Catarina, Brazil",
    bio: "Energizing knowledge, reducing the unknown and advancing transformative innovation. His work approaches complexity by managing chaos and order through Knowledge Engineering, Management and Media, Innovation, Technology and Art. He is currently an AI Analyst at Sebrae/SC, a CAPES doctoral research fellow at the Media Laboratory (LaMiD/PPGEGC/UFSC), a writer and a record producer.",
  },
  experience: [
    {
      period: "06/2026 — Present",
      role: "Technical Analyst II — Artificial Intelligence",
      company: "Sebrae Santa Catarina",
      location: "Florianópolis, SC",
      bullets: [
        "Structuring and operating the governance of Sebrae/SC's AI Office.",
        "Monitoring, analyzing and validating corporate AI projects across technical and support areas, ensuring methodological compliance and quality.",
        "Supporting teams in developing AI project plans, risk matrices, schedules, indicators and expected results.",
        "Monitoring strategic nationwide AI projects aligned with Sebrae Nacional.",
        "Leading technical and compliance assessments of AI use cases and standardizing the solution lifecycle from pilot to production.",
        "Implementing AI performance metrics and monitoring (management-level MLOps/LLMOps) and coordinating training for institutional adoption.",
      ],
    },
    {
      period: "03/2025 — Present",
      role: "CAPES Doctoral Research Fellow",
      company: "Federal University of Santa Catarina (UFSC)",
      location: "Florianópolis, SC",
      bullets: [
        "CAPES research fellow at the Media Laboratory (LaMiD) within UFSC's Graduate Program in Knowledge Engineering, Management and Media (PPGEGC).",
        "Advanced research in knowledge ecology, network science, scientometrics, artificial intelligence and technology governance.",
        "Research on sociotechnical aspects of networked knowledge, including the structure and impact of technologies such as AI in organizational and academic settings.",
      ],
    },
    {
      period: "03/2025 — Present",
      role: "Scientific Reviewer",
      company: "Science Publishing Group",
      location: "International",
      bullets: ["Critical peer review of leading scientific papers in technology, artificial intelligence and knowledge management."],
    },
    {
      period: "01/2024 — 06/2026",
      role: "Innovation, Data and Governance Consultant",
      company: "Independent Consulting / Business",
      location: "Florianópolis, SC",
      bullets: [
        "Consulting in innovation, data, artificial intelligence, knowledge management and technology governance.",
        "Applying methodologies for organizational assessment and planning, indicator monitoring and change management.",
      ],
    },
    {
      period: "08/2023 — 04/2026",
      role: "Senior Innovation Analyst",
      company: "Impact Hub Brazil",
      location: "Florianópolis, SC",
      bullets: [
        "Research, Development and Innovation (R&D&I) for positive social and environmental impact.",
        "Development and implementation of methodologies for Local Innovation and Impact Ecosystems, including co-authorship of the ALI Ecosystems Methodology.",
        "Business intelligence and research on trends and emerging technologies.",
        "Assessment and monitoring of social and environmental impact through systems thinking and executive reporting.",
        "Knowledge management and engineering to capture, share and disseminate organizational practices.",
      ],
    },
    {
      period: "12/2021 — 08/2023",
      role: "Data Analyst",
      company: "Impact Hub Brazil",
      location: "Florianópolis, SC",
      bullets: [
        "Data analysis for innovation ecosystems and social and environmental impact.",
        "Design of analytical pipelines, business intelligence, organizational information governance and learning culture.",
      ],
    },
    {
      period: "04/2020 — 01/2024",
      role: "Co-founder, Record Producer and Audio Engineer",
      company: "VI Mídia Produtora (Visão Inclusiva)",
      location: "Florianópolis, SC",
      bullets: [
        "Co-founder and record producer of accessible educational and entertainment content.",
        "Production of audiobooks, audio description for print-disabled audiences and AI-assisted voice synthesis.",
        "Audio engineering, sound design and digital processing of voice signals.",
        "Owner of a service trademark registered with Brazil's National Institute of Industrial Property (INPI).",
      ],
    },
    {
      period: "04/2020 — 01/2021",
      role: "Literary Editor and Proofreader",
      company: "Noveland Publishing",
      location: "Florianópolis, SC",
      bullets: ["Textual and literary editing, manuscript assessment, editorial coordination and brand management."],
    },
    {
      period: "07/2018 — 02/2020",
      role: "Undergraduate Research Fellow (Robotics R&D)",
      company: "Applied Robotics Laboratory (LAR/UFSC)",
      location: "Florianópolis, SC",
      bullets: [
        "R&D of a robotic inspection system for electric power distribution lines through a Celesc/Mechanical Engineering Department partnership.",
        "Systematic literature review, CAD/SolidWorks modeling, patents, scientific papers and web interface/application development.",
      ],
    },
    {
      period: "01/2017 — 02/2018",
      role: "Engineering Intern",
      company: "CIASC — Santa Catarina Center for Information Technology and Automation",
      location: "Florianópolis, SC",
      bullets: [
        "Development of a predictive monitoring system for a data center.",
        "Sensing and alerts for critical variables such as temperature, humidity, flooding and fire using Zabbix, Arduino and Computational Fluid Dynamics (CFD).",
      ],
    },
    {
      period: "02/2015 — 07/2015",
      role: "Clinical Engineering Intern",
      company: "Institute of Biomedical Engineering (IEB-UFSC / Carmela Dutra)",
      location: "Florianópolis, SC",
      bullets: ["Healthcare Technology Management, quality control, corrective and preventive maintenance, and technical training."],
    },
  ],
  education: [
    {
      period: "01/2025 — 03/2029 (In progress)",
      degree: "PhD in Knowledge Engineering, Management and Media",
      institution: "Federal University of Santa Catarina (UFSC)",
      details: "CAPES fellow. Advisor: Prof. Vânia Ribas Ulbricht, PhD. Focus on Knowledge Ecology, Network Science, Scientometrics, Artificial Intelligence and Sociotechnical Governance.",
    },
    {
      period: "01/2025 — 03/2026 (In progress)",
      degree: "MBA in Technology for Business: AI, Data Science and Big Data",
      institution: "Pontifical Catholic University of Rio Grande do Sul (PUCRS)",
      details: "Executive specialization (364 hours) in artificial intelligence applied to business models, Big Data and strategic decision-making.",
    },
    {
      period: "02/2023 — 02/2025 (Completed)",
      degree: "Master's in Knowledge Engineering and Management",
      institution: "Federal University of Santa Catarina (UFSC)",
      details: "Thesis: 'ECO-CAOS: a conceptual metamodel for knowledge ecosystems and organizational learning cultures.' CAPES fellow. Advisor: Vânia Ribas Ulbricht, PhD. Winner of the SBGC Award for Brazil's Best Master's Thesis.",
    },
    {
      period: "02/2016 — 12/2021 (Completed)",
      degree: "Bachelor's in Electronics Engineering",
      institution: "Federal University of Santa Catarina (UFSC)",
      details: "Undergraduate thesis: 'Adaptive Algorithm for Noise Reduction and Preservation of Binaural Acoustic Cues for Hearing Aids.' Advisor: Prof. Márcio Holsbach Costa, PhD. Emphasis on Digital Signal and Audio Processing.",
    },
    {
      period: "2012 — 2016 (Completed)",
      degree: "Technical Diploma in Electronics",
      institution: "Federal Institute of Santa Catarina (IFSC)",
      details: "Integrated secondary-level technical education grounded in circuits, instrumentation and embedded systems.",
    },
  ],
  certifications: [
    { name: "Data Product Manager Nanodegree", issuer: "Udacity", year: "2021-2022", hours: "160h" },
    { name: "Deep Learning Specialization", issuer: "Coursera / deeplearning.ai", year: "2018", hours: "300h" },
    { name: "Python Programming", issuer: "Coursera", year: "2018", hours: "300h" },
    { name: "Introduction to Linear Models and Matrix Algebra", issuer: "edX / HarvardX", year: "2023" },
    { name: "Digital Marketing Channels: Planning", issuer: "Coursera", year: "2018", hours: "300h" },
    { name: "KM Brazil — Knowledge Management", issuer: "SBGC", year: "2023" },
  ],
  awards: [
    { year: "2025", title: "SBGC Award — Best Master's Thesis", entity: "Brazilian Society for Knowledge Management (SBGC)", description: "National recognition for the ECO-CAOS thesis on knowledge ecosystems and learning culture." },
    { year: "2022", title: "Selected for the 'Everyday Stories' Series", entity: "University Library (BU/UFSC)", description: "Literary work selected for the institutional collection and cultural outreach." },
    { year: "2020", title: "Selected for the Centelha Program", entity: "FAPESC / MCTI / Finep", description: "Government grant and support for VI Mídia's technology innovation and entrepreneurship." },
    { year: "2020", title: "Selected for the Documentary Photography Competition", entity: "Floripa Anônima", description: "Documentary record of the urban landscape and social memory of Santa Catarina Island." },
    { year: "2016", title: "1st IFSC Literature Award — Photography Selection", entity: "Federal Institute of Santa Catarina (IFSC)", description: "Award for an original visual and photographic essay." },
    { year: "2015", title: "Fragmentos do Medo Literary Competition Award", entity: "Três Macacos Premiações", description: "Publication in a nationally distributed flash-fiction anthology." },
    { year: "2014", title: "1st IFSC Short Story Competition Award", entity: "Federal Institute of Santa Catarina (IFSC)", description: "First place and honorable mention in the fiction prose category." },
    { year: "2015 — 2018", title: "Inspiration Award & Rookie All-Star Award", entity: "FIRST Robotics Competition (FRC Team 5800 Magic Island Robotics)", description: "Awards for leadership, communication and community impact in robotics engineering." },
    { year: "2009, 2010, 2011", title: "Three Consecutive Honorable Mentions", entity: "Brazilian Public School Mathematics Olympiad (OBMEP)", description: "Academic distinction in logical reasoning and mathematical problem-solving." },
  ],
  allPublications: cvData.allPublications,
  artisticProduction: [
    {
      category: "Music & Record Production",
      items: [
        "Rancho de Amor à Ilha (2026) — Instrumental lo-fi reinterpretation of Florianópolis's official anthem (original composition by Zininho), celebrating the 100th anniversary of the Hercílio Luz Bridge.",
        "Berimbrasil (@brasil.wav) — A project for curating, promoting and sharing Brazilian music in digital culture.",
        "Albums and Recordings (2020–2024): ColoRio, CacofonIA, CacofonIA 2, Days, Slop, SinfonIA, Data! Data! Data!, Violando, Ruído, Marginal, Centauro, Radiola, Espectros, BON VIVANT, Frutaria, Rizomas, Ludic Dreams, Themes Songbook, Músicas Beta, Músicas Alfa, Quartos.",
        "Original Soundtracks (2021): Heart of Darkness, 1984, O Marinheiro, Boats Against the Current, Triste Fim de Policarpo Quaresma, Hágil (with Gilberto Gil).",
      ],
    },
    {
      category: "Audiobooks & Inclusion",
      items: [
        "A Mecânica das Palavras (2022) — Accessible audiobook.",
        "Retrato do Artista Quando Coisa (Manoel de Barros, 2021) — Accessible audio adaptation.",
        "O Guardador de Rebanhos & O Marinheiro & Mensagem (Fernando Pessoa, 2020–2021) — Audiobook and audio-description production.",
        "The Great Gatsby (F. Scott Fitzgerald, 2021) — Immersive-audio audiobook.",
      ],
    },
    {
      category: "Visual Arts & Photography",
      items: [
        "Nemotom (2021) — Audiovisual work and experimental video.",
        "Floripa Anônima (2020) — Documentary photography essay.",
        "1st IFSC Literature Award (2017) — Award-winning photography series.",
      ],
    },
  ],
  projectsAndMethods: [
    { title: "Media and Digital Inclusion Laboratory (LaMiD / UFSC)", period: "2023 — Present", role: "Researcher / Member", description: "Surveying, analyzing and systematizing research on digital accessibility and knowledge media as mediators of sociotechnical inclusion for people with disabilities." },
    { title: "ALI Ecosystems Methodology", period: "2022", role: "Co-author / Developer", description: "Technical methodology for diagnosing, governing and activating Local Innovation Ecosystems in Brazil, adopted by Sebrae and the Impact Hub network." },
    { title: "Robotic System for Power Grid Inspection (Celesc / LAR-UFSC)", period: "2018 — 2020", role: "Undergraduate Research Fellow", description: "Conceptual design, prototyping, patents and web interface for a robot that inspects electric power distribution lines." },
    { title: "Healthcare Technology Management (CELEC / IEB-UFSC)", period: "2015", role: "Engineering Intern", description: "Comparative study and management of fetal heartbeat detectors at Carmela Dutra Maternity Hospital." },
  ],
  skills: {
    governanceAndKnowledge: [
      "Artificial Intelligence Governance",
      "Knowledge Engineering",
      "Knowledge Ecology",
      "Conceptual Systems Modeling",
      "Organizational Learning Culture",
      "Local Innovation Ecosystems (ELI)",
      "Social and Environmental Impact Management",
    ],
    technical: [
      "MLOps and LLMOps (management and lifecycle level)",
      "Python (Pandas, NumPy, Scikit-Learn, PyTorch)",
      "TypeScript, React, Vite, Node.js",
      "Digital Signal Processing (audio/voice DSP)",
      "Data Modeling and Business Intelligence (BI)",
      "Assistive Technology and Digital Accessibility",
      "Prompt Engineering (Promptography)",
    ],
    languages: [
      { language: "Portuguese", level: "Native" },
      { language: "English", level: "Advanced / Fluent" },
      { language: "Spanish", level: "Professional" },
      { language: "Italian", level: "Intermediate" },
      { language: "French", level: "Basic / Reading" },
    ],
  },
};
