// Content of the creations lab (/criacoes). Kept apart from content.ts so the
// home page bundle doesn't carry it; Tavo reads it on the server too.

export interface Poem {
  slug: string;
  title: string;
  titleEn: string;
  year: string;
  media: "video" | "image" | "canvas";
  ratio: string;
  words: string;
  note: string;
  noteEn: string;
}

export const poems: Poem[] = [
  {
    slug: "pos-estruturalismo",
    title: "Pós-Estruturalismo",
    titleEn: "Post-Structuralism",
    year: "2025",
    media: "video",
    ratio: "1 / 1",
    words: "pós-estruturalismo",
    note: "A palavra é erguida como estrutura empilhada e depois desaba. As sílabas caem, se acumulam no chão e continuam legíveis em ruína: a demolição não apaga o sentido.",
    noteEn: "The word is raised as a stacked structure and then collapses. The syllables fall, pile up on the floor and remain legible in ruin: the demolition does not erase the meaning.",
  },
  {
    slug: "balance-sua-bandeira",
    title: "Balance Sua Bandeira",
    titleEn: "Wave Your Flag",
    year: "2025",
    media: "video",
    ratio: "1000 / 624",
    words: "balance sua bandeira",
    note: "A frase, repetida em faixas, é o próprio tecido de uma bandeira que tremula ao vento. O verso não descreve a bandeira — ele é a bandeira.",
    noteEn: "The phrase, repeated in stripes, is the very fabric of a flag rippling in the wind. The line does not describe the flag — it is the flag.",
  },
  {
    slug: "o-rio-e-o-movimento",
    title: "O Rio e o Movimento",
    titleEn: "The River and the Movement",
    year: "2025",
    media: "video",
    ratio: "1000 / 624",
    words: "o rio existe por conta do movimento\no movimento existe por conta do tempo",
    note: "Os dois versos escorrem em coluna sobre o azul chapado, num fluxo que não chega ao fim. O texto se comporta exatamente como aquilo que enuncia.",
    noteEn: "The two lines pour down a column over flat blue, in a flow that never reaches an end. The text behaves exactly like what it states.",
  },
  {
    slug: "tudo-o-que-eu-queria-te-dizer",
    title: "Tudo o Que Eu Queria Te Dizer",
    titleEn: "Everything I Wanted to Tell You",
    year: "2025",
    media: "video",
    ratio: "1 / 1",
    words: "tudo o que eu queria te dizer",
    note: "A frase começa em serifa nítida e se decompõe em ruído da esquerda para a direita. Sobra o começo; o resto nunca chega inteiro.",
    noteEn: "The sentence begins in crisp serif and decomposes into noise from left to right. The beginning survives; the rest never arrives intact.",
  },
  {
    slug: "eu-senhor-do-meu-fim",
    title: "Eu Senhor do Meu Fim",
    titleEn: "I, Master of My End",
    year: "2025",
    media: "video",
    ratio: "1 / 1",
    words: "eu senhor do meu fim",
    note: "A frase é impressa em fitas coloridas que se entrelaçam num trançado. Ler exige seguir cada tira até onde ela desaparece por baixo da outra: o domínio anunciado depende de uma trama que nunca se vê inteira.",
    noteEn: "The phrase is printed on coloured ribbons woven into a braid. Reading it means following each strip to where it vanishes beneath the next: the mastery announced depends on a weave never seen whole.",
  },
  {
    slug: "a-gente-se-cruza-na-estrada",
    title: "A Gente Se Cruza na Estrada",
    titleEn: "We Cross Paths on the Road",
    year: "2025",
    media: "video",
    ratio: "1 / 1",
    words: "a gente se cruza na estrada",
    note: "A frase percorre um nó que se dobra sobre si mesmo. As linhas se cruzam, se sobrepõem e retornam — o encontro anunciado no verso acontece na geometria.",
    noteEn: "The phrase travels along a knot folding over itself. The lines cross, overlap and return — the encounter announced in the line happens in the geometry.",
  },
  {
    slug: "tudo-por-agua-abaixo",
    title: "Tudo Por Água Abaixo",
    titleEn: "All Down the Drain",
    year: "2025",
    media: "video",
    ratio: "1 / 1",
    words: "tudo por água abaixo",
    note: "A frase desce em espiral por um funil sem fundo, encolhendo até o limite da legibilidade e recomeçando na borda.",
    noteEn: "The phrase spirals down a bottomless funnel, shrinking to the edge of legibility and starting over at the rim.",
  },
  {
    slug: "regenere",
    title: "Regenere",
    titleEn: "Regenerate",
    year: "2025",
    media: "canvas",
    ratio: "1 / 1",
    words: "regenere",
    note: "As letras giram num cilindro. O fim da palavra já é o seu recomeço: regeneração que rege, regeneração que gere.",
    noteEn: "The letters revolve on a cylinder. The end of the word is already its restart: a regeneration that rules, a regeneration that begets — rege and gere both live inside regenere.",
  },
  {
    slug: "rodar-e-rodar",
    title: "Rodar e Rodar",
    titleEn: "Spin and Spin",
    year: "2025",
    media: "video",
    ratio: "1 / 1",
    words: "rodar e rodar",
    note: "Anéis concêntricos de texto branco e vermelho giram em sentidos opostos e produzem moiré. O olho não encontra ponto de repouso.",
    noteEn: "Concentric rings of white and red text spin in opposite directions and produce moiré. The eye finds no place to rest.",
  },
  {
    slug: "poesia-ou-design",
    title: "Poesia ou Design?",
    titleEn: "Poetry or Design?",
    year: "2025",
    media: "video",
    ratio: "1 / 1",
    words: "poesia ou design?",
    note: "A pergunta se repete em linhas finíssimas que giram no espaço, ora legíveis, ora comprimidas até virar pura textura. Meta-poema da série: a mesma matéria oscila entre as duas respostas.",
    noteEn: "The question repeats in hairline rows turning in space, now legible, now compressed into pure texture. The series' meta-poem: the same matter oscillates between both answers.",
  },
  {
    slug: "o-futuro-e-imenso",
    title: "O Futuro é Imenso",
    titleEn: "The Future Is Immense",
    year: "2025",
    media: "video",
    ratio: "384 / 734",
    words: "o futuro é imenso",
    note: "A frase se estilhaça em cópias vermelhas, verdes e azuis que se afastam do centro e voltam a coincidir. A separação dos canais de cor vira medida de amplitude.",
    noteEn: "The phrase shatters into red, green and blue copies that drift from the centre and fall back into register. Colour-channel separation becomes a measure of magnitude.",
  },
  {
    slug: "o-todo-e-muita-coisa",
    title: "O Todo é Muita Coisa",
    titleEn: "The Whole Is a Lot",
    year: "2025",
    media: "video",
    ratio: "384 / 734",
    words: "o todo é muita coisa",
    note: "Raios de luz irradiam de dentro das letras, ora ofuscando a frase, ora devolvendo-a à leitura. O excesso é o assunto e também a técnica.",
    noteEn: "Rays of light radiate from inside the letters, now blinding the phrase, now handing it back to be read. Excess is both the subject and the technique.",
  },
  {
    slug: "meu-sonho-meu-pesadelo",
    title: "O Meu Sonho Também é Meu Pesadelo",
    titleEn: "My Dream Is Also My Nightmare",
    year: "2025",
    media: "image",
    ratio: "1400 / 876",
    words: "o meu sonho também é meu pesadelo",
    note: "Imagem fixa. Metade da frase permanece em serifa estável; a outra metade é corroída por glitch. A imagem se parte exatamente onde a frase se inverte.",
    noteEn: "A still image. Half the sentence stays in stable serif; the other half is eaten by glitch. The image breaks exactly where the sentence turns on itself.",
  },
  {
    slug: "nome-proprio-i",
    title: "Nome Próprio I",
    titleEn: "Proper Noun I",
    year: "2025",
    media: "video",
    ratio: "1000 / 624",
    words: "gustavo simas",
    note: "Primeira das quatro variações sobre o próprio nome. Blocos alternados de preto e branco formam um tabuleiro que uma onda atravessa, deslocando as letras sem nunca desfazer a grade.",
    noteEn: "First of four variations on the artist's own name. Alternating black and white blocks form a board crossed by a wave that shifts the letters without ever undoing the grid.",
  },
  {
    slug: "nome-proprio-ii",
    title: "Nome Próprio II",
    titleEn: "Proper Noun II",
    year: "2025",
    media: "video",
    ratio: "1000 / 626",
    words: "gustavo simas",
    note: "Milhares de repetições em escala decrescente comprimem o nome até virar moiré. Quando as camadas se afastam, o nome volta a ser apenas um nome.",
    noteEn: "Thousands of repetitions at decreasing scale compress the name into moiré. As the layers pull apart, the name becomes just a name again.",
  },
  {
    slug: "nome-proprio-iii",
    title: "Nome Próprio III",
    titleEn: "Proper Noun III",
    year: "2025",
    media: "video",
    ratio: "1000 / 624",
    words: "gustavo simas",
    note: "A mesma grade da primeira variação, agora em vermelho, azul e branco sobre amarelo saturado. A ondulação que era sombra vira cor.",
    noteEn: "The same grid as the first variation, now in red, blue and white on saturated yellow. The ripple that was shadow becomes colour.",
  },
  {
    slug: "nome-proprio-iv",
    title: "Nome Próprio IV",
    titleEn: "Proper Noun IV",
    year: "2025",
    media: "video",
    ratio: "1000 / 626",
    words: "gustavo simas",
    note: "Última variação: o nome ocupa a tela inteira em pesos, inclinações e recortes que se substituem, alternando positivo e negativo até esgotar as formas possíveis.",
    noteEn: "Final variation: the name fills the whole frame in weights, slants and crops that replace one another, alternating positive and negative until the possible forms run out.",
  },
];

export const creationExperiments = [
  {
    title: "LIFE∞ — Infinite Life Lab",
    titleEn: "LIFE∞ — Infinite Life Lab",
    description: "Um laboratório do Jogo da Vida de Conway em tela infinita, para desenhar padrões, acompanhar métricas e observar emergência, auto-organização e vida artificial acontecerem sozinhas.",
    descriptionEn: "A Conway's Game of Life laboratory on an infinite canvas, for drawing patterns, tracking metrics and watching emergence, self-organization and artificial life happen on their own.",
    tag: "Vida artificial",
    tagEn: "Artificial life",
    href: "https://gameoflife.gustavosimas.com/",
  },
  {
    title: "LENIA∞ — Continuous Life Lab",
    titleEn: "LENIA∞ — Continuous Life Lab",
    description: "Um laboratório de Lenia e SmoothLife, autômatos celulares contínuos em 2D e 3D: kernel de anel, função de crescimento, câmera livre e renderização volumétrica para ver a vida emergir sem grade nem passo discreto.",
    descriptionEn: "A laboratory of Lenia and SmoothLife, continuous cellular automata in 2D and 3D: ring kernel, growth function, free camera and volumetric rendering to watch life emerge with no grid and no discrete step.",
    tag: "Vida artificial",
    tagEn: "Artificial life",
    href: "https://smoothlife.gustavosimas.com/",
  },
  {
    title: "PARTICLES∞ — Emergent Matter Lab",
    titleEn: "PARTICLES∞ — Emergent Matter Lab",
    description: "Um laboratório de vida por partículas: milhares de pontos coloridos que só sabem se atrair ou se repelir uns aos outros e, dessa regra mínima, formam células, membranas, enxames e organismos que ninguém programou.",
    descriptionEn: "A particle life laboratory: thousands of colored dots that only know how to attract or repel one another and, from that minimal rule, form cells, membranes, swarms and organisms nobody programmed.",
    tag: "Vida artificial",
    tagEn: "Artificial life",
    href: "https://particlelife.gustavosimas.com/",
  },
];

export const creationsCopy = {
  pt: {
    back: "Voltar ao site",
    themeAria: "Alternar tema",
    languageAria: "Mudar idioma para inglês",
    kicker: "Laboratório",
    title: "Criações",
    lede: "O que não cabe exatamente no currículo. Experimentos, poemas visuais, brinquedos computacionais e ideias que existem porque eu quis ver como ficariam. Uma pesquisa contínua das possibilidades de expressão em diferentes mídias.",
    poems: {
      number: "02",
      label: "Poemas visuais animados",
      title1: "A palavra",
      title2: "como matéria.",
      subtitle: "Série de poemas digitais em que a frase deixa de ser suporte do sentido e vira corpo: bandeira, relógio, rio, estrutura que desaba. Clique em qualquer peça para vê-la inteira, com o texto e uma nota sobre o procedimento.",
      open: "Abrir peça",
      close: "Fechar",
      words: "Texto",
      about: "Procedimento",
      play: "Reproduzir",
      still: "Imagem fixa",
      galleryAria: "Galeria de poemas visuais",
      searchLabel: "Buscar",
      searchPlaceholder: "Título, texto ou ano",
      searchAria: "Buscar poemas visuais",
      searchClear: "Limpar busca",
      counter: "peças",
      counterOne: "peça",
      empty: "Nenhuma peça encontrada para esta busca.",
      previous: "Anteriores",
      next: "Próximas",
      page: "Página",
      pageOf: "de",
      pagerAria: "Paginação da galeria de poemas",
    },
    interactive: {
      number: "01",
      label: "Poemas interativos",
      title1: "Cinco poemas",
      title2: "que respondem.",
      subtitle: "Um relógio que marca o horário de Brasília em tempo real, com as letras sendo arrastadas pelo tempo, uma bandeira que balança a sua frase, uma palavra desenhada pela repetição de outra, um chão onde as palavras caem e se desmancham em letras e um letreiro de néon que foge de quem tenta tocá-lo.",
      clockTitle: "O Tempo Não Para",
      clockNote: "O tempo arrasta as palavras. “Não sei o que é o tempo. Não sei qual a verdadeira medida que ele tem, se tem alguma. A do relógio sei que é falsa: divide o tempo espacialmente, por fora” — Fernando Pessoa. Relógio no horário de Brasília.",
      clockLabel: "Horário de Brasília",
      clockAria: "Relógio em tempo real com as letras da frase o tempo não para sendo arrastadas pelo ponteiro dos segundos",
      flagTitle: "Balance Sua Bandeira",
      flagNote: "As palavras texto e tecido vêm da mesma raiz em latim, texere, que significa “tecer”, “entrelaçar” ou “construir”. Seu texto tremulando ao vento.",
      flagInput: "Escreva a sua palavra",
      flagHint: "Até 42 caracteres. Deixe em branco para ver a frase original.",
      flagLight: "Faixa clara",
      flagDark: "Faixa escura",
      flagBackground: "Fundo",
      flagReset: "Restaurar",
      flagExport: "Baixar a sua bandeira",
      flagExporting: "Gerando o arquivo…",
      flagAria: "Bandeira animada feita com a frase digitada pelo visitante",
      mosaicTitle: "Topograma",
      mosaicNote: "Homenagem ao LUXO/LIXO de Augusto de Campos: uma palavra deixa de ser lida e passa a servir só de molde para outra. Escreva a palavra que aparece e a palavra que a preenche — a segunda se repete até desenhar cada letra da primeira, e o que se lê depende da distância de quem olha.",
      mosaicStencil: "Palavra que aparece",
      mosaicStencilPlaceholder: "LIXO",
      mosaicTile: "Palavra que preenche",
      mosaicTilePlaceholder: "LUXO",
      mosaicOverview: "Visão geral",
      mosaicReading: "Ler preenchimento",
      mosaicReadingHint: "Role a área ampliada para explorar; com o teclado, use as setas após focar o poema. A animação fica pausada nesta leitura.",
      mosaicMode: "Modo de composição",
      mosaicModeFlow: "Palavra contínua",
      mosaicModeWhole: "Palavras inteiras",
      mosaicHint: "Até 12 caracteres em cada campo. Em «palavra contínua» o texto corre e é recortado pelas letras; em «palavras inteiras» nenhuma palavra é cortada. Use «Ler preenchimento» para ampliar as palavras menores. Deixe em branco para ver o par original.",
      mosaicAria: "Canvas com uma palavra grande desenhada pela repetição de outra palavra menor",
      gravityTitle: "A Gravidade da Palavra",
      gravityNote: "Toda palavra escrita aqui se desfaz ao cair: as letras se soltam umas das outras e passam a obedecer só à gravidade, ao atrito e ao acaso das colisões. No chão, porém, elas voltam a se juntar: arraste uma letra até encostar noutra e as duas se colam numa linha só. Do que sobrou de GRAVIDADE se tira VAIDADE. A palavra colada passa a cair, tombar e empilhar como peça inteira; dois cliques nela desmancham tudo de novo.",
      gravitySeed: "gravidade",
      gravityInput: "Escreva uma palavra",
      gravityPlaceholder: "queda",
      gravityAdd: "Soltar",
      gravityUpdate: "Atualizar",
      gravityFont: "Fonte das letras",
      gravityColour: "Cor",
      gravityClear: "Limpar o chão",
      gravityEdit: "Editar palavra",
      gravityDelete: "Apagar palavra",
      gravityEmpty: "Nada caiu ainda.",
      gravityHint: "Até 28 caracteres por palavra · clique numa palavra para editar · arraste uma letra até outra para colá-las · dois cliques desmancham a palavra colada.",
      gravityAria: "Canvas com física de gravidade onde as letras caem, colidem, se empilham e se colam umas nas outras quando arrastadas",
      gravityPull: "Gravidade",
      gravityBounce: "Quique",
      gravityGrip: "Atrito",
      gravityReset: "Física original",
      touchTitle: "Não Toque É Arte",
      touchNote: "O aviso de museu virado poema. A frase acende em néon e troca de cor sem parar, mas não se deixa alcançar: quanto mais perto o cursor chega, com mais força as letras empurram e escapam pelos lados. Tire o mouse e o letreiro se remonta sozinho, na mesma linha de antes. A obra só continua inteira enquanto ninguém toca nela.",
      touchLabel: "Aproxime o cursor",
      touchAria: "Canvas com a frase não toque é arte em letras luminosas que mudam de cor e fogem do cursor do mouse",
    },
    experiments: {
      number: "03",
      label: "Experimentos e laboratórios",
      title1: "Experimentos de",
      title2: "vida artificial",
      subtitle: "Peças que funcionam operando algo que não estava previsto.",
      open: "Abrir experimento",
      openTitle: "Em aberto",
      openText: "Este espaço continua sendo escrito. Novos experimentos entram aqui conforme saem do papel.",
    },
    zine: {
      number: "04",
      label: "Publicação experimental",
      title: "Reciclopédia Concreta",
      text: "Um caderno de poesia visual reunindo peças tipográficas em página fixa, uma versão impressa de investigação similar a que aqui se move.",
      open: "Em breve...",
      alt: "Capa da Reciclopédia Concreta",
    },
    footer: "Criações · experimentos · poemas visuais",
  },
  en: {
    back: "Back to site",
    themeAria: "Switch theme",
    languageAria: "Mudar idioma para português",
    kicker: "Laboratory",
    title: "Creations",
    lede: "What doesn't quite fit in a CV. Experiments, visual poems, computational toys and ideas that exist because I wanted to see how they would turn out. A continuous investigation into the possibilities of expression across different media.",
    poems: {
      number: "02",
      label: "Animated visual poems",
      title1: "The word",
      title2: "as matter.",
      subtitle: "A series of digital poems in which the sentence stops carrying meaning and becomes a body: a flag, a clock, a river, a structure that collapses. Click any piece to see it whole, with its text and a note on the procedure.",
      open: "Open piece",
      close: "Close",
      words: "Text",
      about: "Procedure",
      play: "Play",
      still: "Still image",
      galleryAria: "Visual poems gallery",
      searchLabel: "Search",
      searchPlaceholder: "Title, text or year",
      searchAria: "Search visual poems",
      searchClear: "Clear search",
      counter: "pieces",
      counterOne: "piece",
      empty: "No piece matches this search.",
      previous: "Previous",
      next: "Next",
      page: "Page",
      pageOf: "of",
      pagerAria: "Poem gallery pagination",
    },
    interactive: {
      number: "01",
      label: "Interactive poems",
      title1: "Five poems",
      title2: "that answer back.",
      subtitle: "A clock running on real Brasília time, its letters dragged along by time itself, a flag that waves your own words, a word drawn by the repetition of another, a floor where words fall and come apart into letters, and a neon sign that runs from anyone who tries to touch it.",
      clockTitle: "O Tempo Não Para",
      clockNote: "Time drags the words along. “I do not know what time is. I do not know its true measure, if it has one. The clock’s I know to be false: it divides time spatially, from the outside” — Fernando Pessoa. A clock running on Brasília time.",
      clockLabel: "Brasília time",
      clockAria: "Real-time clock with the letters of the phrase o tempo não para dragged along by the second hand",
      flagTitle: "Balance Sua Bandeira",
      flagNote: "The words text and textile share the same Latin root, texere: to weave, to interlace, to build. Your text, rippling in the wind.",
      flagInput: "Write your own words",
      flagHint: "Up to 42 characters. Leave it empty for the original phrase.",
      flagLight: "Light stripe",
      flagDark: "Dark stripe",
      flagBackground: "Background",
      flagReset: "Reset",
      flagExport: "Download your flag",
      flagExporting: "Building the file…",
      flagAria: "Animated flag built from the phrase typed by the visitor",
      mosaicTitle: "Topograma",
      mosaicNote: "After Augusto de Campos' LUXO/LIXO: one word stops being read and becomes nothing but the mould of another. Write the word that shows and the word that fills it — the second repeats itself until it draws every letter of the first, and what you read depends on how far away you stand.",
      mosaicStencil: "Word that shows",
      mosaicStencilPlaceholder: "LIXO",
      mosaicTile: "Word that fills it",
      mosaicTilePlaceholder: "LUXO",
      mosaicOverview: "Overview",
      mosaicReading: "Read the filling",
      mosaicReadingHint: "Scroll the enlarged area to explore; with a keyboard, focus the poem and use the arrow keys. Animation is paused in this view.",
      mosaicMode: "Composition mode",
      mosaicModeFlow: "Running text",
      mosaicModeWhole: "Whole words",
      mosaicHint: "Up to 12 characters in each field. In \u201crunning text\u201d the words flow and get cut by the letters; in \u201cwhole words\u201d nothing is ever cut open. Use “Read the filling” to enlarge the smaller words. Leave them empty for the original pair.",
      mosaicAria: "Canvas with a large word drawn by the repetition of a smaller word",
      gravityTitle: "The Gravity of the Word",
      gravityNote: "Every word written here comes apart as it falls: the letters break loose from one another and start obeying nothing but gravity, friction and the chance of collisions. On the floor, though, they can be put back together: drag one letter until it touches another and the two weld into a single row, spelling whatever the wreckage allows. A welded word then falls, tips and stacks as one piece; double-click it to break it apart again.",
      gravitySeed: "gravity",
      gravityInput: "Write a word",
      gravityPlaceholder: "fall",
      gravityAdd: "Drop",
      gravityUpdate: "Update",
      gravityFont: "Letter typeface",
      gravityColour: "Colour",
      gravityClear: "Clear the floor",
      gravityEdit: "Edit word",
      gravityDelete: "Delete word",
      gravityEmpty: "Nothing has fallen yet.",
      gravityHint: "Up to 28 characters per word · click a word to edit it · drag one letter onto another to weld them · double-click a welded word to break it apart.",
      gravityAria: "Canvas with gravity physics where letters fall, collide, pile up and weld to one another when dragged together",
      gravityPull: "Gravity",
      gravityBounce: "Bounce",
      gravityGrip: "Friction",
      gravityReset: "Default physics",
      touchTitle: "Não Toque É Arte",
      touchNote: "The museum warning turned into a poem. The phrase burns in neon and never stops shifting colour, but it will not be reached: the closer the cursor gets, the harder the letters shove back and slip aside. Move the mouse away and the sign puts itself back together on the same line. The work stays whole only as long as nobody touches it.",
      touchLabel: "Bring the cursor closer",
      touchAria: "Canvas with the phrase não toque é arte in luminous letters that shift colour and flee from the mouse cursor",
    },
    experiments: {
      number: "03",
      label: "Experiments and labs",
      title1: "Experiments in",
      title2: "artificial life",
      subtitle: "Pieces that work by setting in motion something that was not foreseen.",
      open: "Open experiment",
      openTitle: "Open-ended",
      openText: "This space is still being written. New experiments land here as they leave the drawing board.",
    },
    zine: {
      number: "04",
      label: "Experimental publication",
      title: "Reciclopédia Concreta",
      text: "A visual poetry notebook gathering typographic pieces on the fixed page, a printed version of an investigation similar to the one that moves here.",
      open: "Coming soon...",
      alt: "Cover of Reciclopédia Concreta",
    },
    footer: "Creations · experiments · visual poems",
  },
};
